version: '3'
services:
  app-nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-nodejs
    command: sh -c "npm init -y && npm install mysql express jest supertest --save && node app.js"  
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
